version: '2'

services:
  mysql:
    container_name: notes-mysql
    image: mysql:5.6.34
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: notes
      MYSQL_ROOT_PASSWORD: notes
      MYSQL_DATABASE: notes
    volumes:
      - ./data:/var/lib/mysql
    user: mysql